use student;
insert into users(id,username,created_at) values (2,'李华',now());
insert into users(id,username,created_at) values (3,'王芳',now());
select * from users order by id asc;
select * from users order by id desc;
select * from users where username='李华';
select * from users where id=1;
select * from users limit 2;
select * from users limit 1,2;
select count(*) as 总数 from users;
select count(*) from users where id>1;
create table orders(id int primary key,user_id int not null,amount int,created_at datetime);
insert into orders(id,user_id,amount,created_at) values(1,1,100,now()),(2,1,200,now()),(3,2,150,now());
select sum(amount) from orders;
select sum(amount) from orders where user_id=1;
select avg(amount) from orders;
select avg(amount) from orders where user_id=2;
select user_id,count(amount) from orders group by user_id;
select user_id,sum(amount) from orders group by user_id;
create table products (id int primary key, name varchar(100) not null, price int);
insert into products values (1, '鼠标', 50);
insert into products values (2, '键盘', 120);
update products set price=60 where id=1;
update users set username='王芳芳' where id=3;
delete from products where id=1; 
delete from users where username='王芳芳';